#! /bin/sh
#
#Copyright (c) 2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# mpdecision        init.d script to start mpdecision

set -e

case "$1" in
  start)
        echo -n "Starting mpdecision: "
        start-stop-daemon -S -b -x /usr/bin/mpdecision
        echo "done"
        ;;
  stop)
        echo -n "Stopping mpdecision: "
        start-stop-daemon -K -n mpdecision
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start

