#!/bin/bash
###############################################################################
## Copyright (c) 2012-2015 Qualcomm Technologies, Inc.
## All Rights Reserved.
## Confidential and Proprietary - Qualcomm Technologies, Inc.
###############################################################################

MACHINE_EAGLE8074=eagle8074
MACHINES="${MACHINE_EAGLE8074}"
DEFAULT_MACHINE=${MACHINE_EAGLE8074}

IMAGE_QRL_BINARIES=qrl-binaries
IMAGE_PERSIST=persist
IMAGE_SDK=meta-ide-support
IMAGES="${IMAGE_QRL_BINARIES} ${IMAGE_PERSIST}"
DEFAULT_IMAGE=${IMAGE_QRL_BINARIES}

DPKG_CMD="dpkg-query"

optMachine=${DEFAULT_MACHINE}
optImage=

imagesToBuild=

# Exit on error
set -e

################################################################################
## usage
################################################################################
usage ()
{
    cat << EOF
This scripts builds the QR-Linux kernel and other necessary images
USAGE: $0 options
OPTIONS:
   -h      Show this message
   -b      Skip building the bootloader
   -m      The machine to build (default: ${DEFAULT_MACHINE})
   -i      The image to build (default: ${DEFAULT_IMAGE})
EOF

    echo
    echo "Valid machine values are:"
    for machine in ${MACHINES}
    do
        echo "    $machine"
    done
    echo
    echo
    echo "Valid image values are:"
    for image in ${IMAGES}
    do
        echo "    $image"
    done
}

################################################################################
## handleCommandLine
################################################################################
handleCommandLine () {
    while getopts "hm:i:" o
    do
        case $o in
        h)
            usage
            exit 1
            ;;
        m)
            optMachine=$OPTARG
            ;;
        i)
            optImage=$OPTARG
            ;;
        ?)
            echo "Unknown arg $o"
            usage
            exit
            ;;
        esac
    done

    foundMachine=0
    for machine in ${MACHINES}
    do
        if [[ ${optMachine} = ${machine} ]]
        then
            foundMachine=1
        fi
    done

    if [[ $foundMachine -eq 0 ]]
    then
        echo "[ERROR] Unsupported machine: ${optMachine}"
        echo
        echo "Valid machine values are:"
        for machine in ${MACHINES}
        do
            echo "    $machine"
        done
        exit 1
    fi

    if [[ -z ${optImage} ]]
    then
        imagesToBuild=(${IMAGE_QRL_BINARIES} ${IMAGE_PERSIST})
        x="${IMAGE_QRL_BINARIES} -c image"
        IFS=""
        imagesToBuild=("$x")
        if [[ ${optMachine} = ${MACHINE_EAGLE8074} ]]
        then
            # Add SDK as another build product
            x="${IMAGE_SDK}"
            imagesToBuild=("${imagesToBuild[@]}" "$x")
        fi
    else
        foundImage=0
        for image in ${IMAGES}
        do
            if [[ ${optImage} = ${image} ]]
            then
                foundImage=1
                imagesToBuild=(${optImage})
            fi
        done

        if [[ $foundImage -eq 0 ]]
        then
            echo "[ERROR] Unsupported image: ${optImage}"
            echo
            echo "Valid image values are:"
            for image in ${IMAGES}
            do
                echo "    $image"
            done
            exit 1
        fi
    fi
}

################################################################################
## checkRequiredPkgs
################################################################################
checkRequiredPkgs () {
    type ${DPKG_CMD} > /dev/null 2>&1 || {
        echo "[ERROR] ${DPKG_CMD} not found. Can't check for installed packages"
        return 1
    }

    pkgMissing=0
    pkgsMissing="Packages missing: "
    for pkg in diffstat texinfo gawk chrpath
    do
        ${DPKG_CMD} --status ${pkg} > /dev/null 2>&1
        if [ $? -ne 0 ]
        then
            pkgMissing=1
            pkgsMissing="${pkgsMissing} ${pkg}"
        fi
    done

    if [ ${pkgMissing} = 1 ]
    then
        echo "[ERROR] Check for required packages failed. ${pkgsMissing}"
        return 1
    fi
    return ${pkgMissing}
}

################################################################################
## configureLayers
##    This is slightly tricky.
##    We add additional layers to the bblayers.conf file. We also add
##    a comment string to that file. When the script is re-run, it
##    checks for the existence of the comment line, and skips adding
##    the layers all over again.
################################################################################
configureLayers () {
   bblayersFile=build/conf/bblayers.conf
   commentString="# Additional layers for proprietary use -- autogenerated by build script"

    if [ ! -f ${bblayersFile} ]
    then
        echo "[ERROR] Unable to find ${bblayersFile}. Are you running from the top of the tree?"
        exit 1
    fi

    grep "${commentString}" ${bblayersFile} > /dev/null 2>&1 || {
        echo ${commentString} >> ${bblayersFile}
        for layer in meta-qti meta-qti-prebuilt
        do
            echo "BBLAYERS += \"\${TOPDIR}/../${layer}\"" >> ${bblayersFile}
        done
        return 0
    }

	return 0
}

################################################################################
## main
################################################################################

export TEMPLATECONF=meta-qr-linux/conf

handleCommandLine $@
echo "[INFO] Building machine: ${optMachine}. Images: ${imagesToBuild[@]}"
checkRequiredPkgs || {
    echo "[ERROR] Can't build because of missing build tools"
    exit 1
}

echo "[INFO] Fetching toolchain"
meta-qr-linux/scripts/linaro-fetch.sh

configureLayers
source ./oe-init-build-env build

for img in "${imagesToBuild[@]}"
do
    echo "[INFO] Building image: ${img}"
    eval MACHINE=${optMachine} bitbake ${img}
done
